---
title: "README"
output: 
    github_document:
        toc: true
---
# Authenticating the Terraform Workflow to your Azure Environment
## Setting up GitHub Actions OIDC Authentication {.tabset .tabset-pills}
OpenID Connect (OIDC) allows your GitHub Actions workflows to access resources in Azure, without needing to store the Azure credentials as long-lived GitHub secrets.

### Create an Azure Active Directory Application and Service Principal

#### Azure Portal
    
1. If you do not have an existing application, register a new Azure Active Directory application and service principal that can access resources. As part of this process, make sure to:
    * Register your application with Azure AD and create a service principal
    * Assign a role to the application
2. Open App registrations in Azure portal and find your application. Copy the values for Application (client) ID and Directory (tenant) ID to use in your GitHub Actions workflow.

3. Open Subscriptions in Azure portal and find your subscription. Copy the Subscription ID.

#### Azure CLI

1. Create the Azure Active Directory application.
    ```{az}
    az ad app create --display-name myApp
    ```
    This command will output JSON with an ```appId``` that is your ```client-id```. The ```objectId``` is ```APPLICATION-OBJECT-ID``` and it will be used for creating federated credentials with Graph API calls.
2. Create a service principal. Replace ```$appIdD``` with the appId from your JSON output. This command generates JSON output with a different ```objectId``` will be used in the next step. The new ```objectId``` is the ```assignee-object-id```.
    ```{az}
    az ad sp create --id $appId
    ```
3. Create a new role assignment by subscription and object. By default, the role assignment will be tied to your default subscription. Replace ```$subscriptionId``` with your subscription ID, ```$resourceGroupName``` with your resource group name, and ```$assigneeObjectId``` with generated ```assignee-object-id``` (the newly created service principal object id).
    ```{az}
    az role assignment create --role contributor --subscription $subscriptionId --assignee-object-id  $assigneeObjectId --assignee-principal-type ServicePrincipal --scope /subscriptions/$subscriptionId/resourceGroups/$resourceGroupName
    ```
#### Azure PowerShell

1. Create the Azure Active Directory application.
    ```{powershell}
    New-AzADApplication -DisplayName myApp
    ```
    This command will output the ```AppId``` property that is your ```ClientId```. The ```Id``` property is ```APPLICATION-OBJECT-ID``` and it will be used for creating federated credentials with Graph API calls.
2. Create a service principal. Replace the ```$clientId``` with the AppId from your output. This command generates output with a different ```Id``` and will be used in the next step. The new ```Id``` is the ```objectId```.
    ```{powershell}
    $clientId = (Get-AzADApplication -DisplayName myApp).AppId
    New-AzADServicePrincipal -ApplicationId $clientId
    ```
3. Create a new role assignment. Beggining with Az PowerShell module version 7.x, ```New-AzAdServicePrincipal``` no longer assigned the contributor role to the service principal by default. Replace ```$resourceGroupName``` with your resource group name, and ```$objectId``` with the generated ```Id```.
    ```{powershell}
    $objectId = (Get-AzADServicePrincipal -DisplayName myApp).Id
    New-AzRoleAssignment -ObjectId $objectId -RoleDefinitionName Contributor -ResourceGroupName $resourceGroupName
    ```
4. Get the values for ```clientId```, ```subscriptionId```, and ```tenantId``` to use later in your GitHub Actions workflow.
    ```{powershell}
    $clientId = (Get-AzADApplication -DisplayName myApp).AppId
    $subscriptionId = (Get-AzContext).Subscription.Id
    $tenantId = (Get-AzContext).Subscription.TenantId
    ```