name: Terraform Lint

on:
  push:
    branches:
      - !main
      - !dev
  pull_request: 
    branches: 
      - main
      - dev
  
  jobs: 
    terraform_lint:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0