name: Terraform Lint

on:
  push:
  pull_request: 
    branches: 
      - main
      - dev
  
jobs: 
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        id: checkout
        uses: actions/checkout@v2
      - name: generate github token
        uses: tibdex/github-app-token@v1
        id: github_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Terraform Lint
        id: lint1
        run: |
          terraform fmt -check -diff
      - name: Terraform fmt list
        if: ${{ failure() }}
        id: lint2
        run: |
          terraform fmt -check -list=true
      - id: diff
        if: ${{ failure() }}
        run: |
          echo '${{ steps.lint1.outputs.stdout || steps.lint1.outputs.stderr }}' \
          | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > diff.txt && \
          echo '${{ steps.lint2.outputs.stdout || steps.lint2.outputs.stderr }}' > list.txt
      - name: Put diff and list in Env Var
        if: ${{ failure() }}
        run: |
          DIFF=$(cat diff.txt)
          echo "DIFF<<EOF" >> $GITHUB_ENV
          echo "$DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          LIST=$(cat list.txt)
          echo "LIST<<EOF" >> $GITHUB_ENV
          echo "$LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post Diff to GitHub PR
        uses: mshick/add-pr-comment@v1
        if: ${{ failure() }}
        with:
          allow-repeats: true
          repo-token: ${{ steps.generate-token.outputs.token }}
          message: |
            ## Terraform Format Diff:
            ```diff
            ${{ env.DIFF }}
            ```

            ## List of files:
            ${{ env.LIST }}
      - name: Post Success to GitHub PR
        uses: mshick/add-pr-comment@v1
        if: ${{ success() }}
        with:
          allow-repeats: true
          repo-token: ${{ steps.generate-token.outputs.token }}
          message: |
            ## :smiley: Linting successful!
    
